#!/usr/bin/env python
import sys

if len(sys.argv)<3 :
    print "Usage:"
    print " %s A B [C ...]"%sys.argv[0]
    print "will remove the runs present in B [C...] from A and print the result to stdout."
    sys.exit()

def jsonFromFile(fileName = "") :
    with open(fileName) as f : 
        return eval(f.read())

orig = jsonFromFile(sys.argv[1])
popRuns = sum([jsonFromFile(name).keys() for name in sys.argv[2:]],[])

for run in set(popRuns) :
    if run in orig : orig.pop(run)

print str(orig).replace("'",'"')
