#!/usr/bin/env python
import sys

if len(sys.argv)<3 :
    print "Usage:"
    print " %s A B [C ...]"%sys.argv[0]
    print "will remove the runs present in B [C...] from A and print the result to stdout."
    sys.exit()

def dictRead(fileName = "") :
    f = open(fileName)
    out = f.read()
    f.close()
    return eval(out)

out = dictRead(fileName = sys.argv[1])

for arg in sys.argv[2:] :
    d = dictRead(fileName = arg)
    for key in d.keys() :
        if key in out : del out[key]

print str(out).replace("'",'"')
