#!/usr/bin/env python
import sys,os
from core import utils

if len(sys.argv)<3 :
    os.system(' '.join(['hadd']+sys.argv[1:]))
    sys.exit()

nCores = 4
nMax = 20
options = ' '.join(filter(lambda a: a[0]=='-', sys.argv[1:]))
target = filter(lambda a: a[0]!='-', sys.argv[1:])[0]
sources = filter(lambda a: a[0]!='-', sys.argv[1:])[1:]
nJobs = 1 + len(sources)/nMax

commands = ['hadd %s %s %s'%(options,target+str(iJob),' '.join(sources[iJob::nJobs]))
            for iJob in range(nJobs)]

utils.operateOnListUsingQueue( nCores, utils.qWorker(utils.getCommandOutput), zip(commands) )

hAdd = utils.getCommandOutput('hadd %s %s %s'%(options,target,' '.join(target+str(iJob) for iJob in range(nJobs))))
for iJob in range(nJobs) : os.remove(target+str(iJob))
sys.stderr.write(hAdd["stderr"])
sys.stdout.write(hAdd["stdout"])
sys.exit()
