#!/usr/bin/env python

import os,sys,tempfile

if len(sys.argv)<3 :
    print "Usage: %s file1.pdf file2.pdf"%sys.argv[0]
    exit()

tmp = tempfile.mkdtemp()
names = [{"pdf":sys.argv[i], "ps":"%s/%s"%(tmp, sys.argv[i].replace("/","_"))} for i in range(1,3)]

for d in names :
    os.system("pdftops %s %s"%(d["pdf"], d["ps"]))

os.system("diff %s %s"%(names[0]["ps"], names[1]["ps"]))

for d in names :
    if os.path.exists(d["ps"]) : os.remove(d["ps"])

os.rmdir(tmp)
